let properties: Array<any> = [
    {
        id: 1,
        address: "18 Henry st",
        city: "Cambridge",
        state: "MA",
        zip: "01742",
        age: "12",
        title: "Player",        
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet"        
    },
    {
        id: 2,
        address: "18 Henry st",
        city: "Cambridge",
        state: "MA",
        zip: "01742",
        age: "12",
        title: "Player",        
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet"        
    },
    {
        id: 3,
        address: "18 Henry st",
        city: "Cambridge",
        state: "MA",
        zip: "01742",
        age: "12",
        title: "Player",        
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet"        
    },
    {
        id: 4,
        address: "18 Henry st",
        city: "Cambridge",
        state: "MA",
        zip: "01742",
        age: "12",
        title: "Player",        
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet"        
    },
    {
        id: 5,
        address: "18 Henry st",
        city: "Cambridge",
        state: "MA",
        zip: "01742",
        age: "12",
        title: "Player",        
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet"        
    },
    {
        id: 6,
        address: "18 Henry st",
        city: "Cambridge",
        state: "MA",
        zip: "01742",
        age: "12",
        title: "Player",        
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet"        
    },
    {
        id: 7,
        address: "18 Henry st",
        city: "Cambridge",
        state: "MA",
        zip: "01742",
        age: "12",
        title: "Player",        
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet"        
    },
    {
        id: 8,
        address: "18 Henry st",
        city: "Cambridge",
        state: "MA",
        zip: "01742",
        age: "12",
        title: "Player",        
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet"        
    },
    {
        id: 9,
        address: "18 Henry st",
        city: "Cambridge",
        state: "MA",
        zip: "01742",
        age: "12",
        title: "Player",        
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet"        
    },
    {
        id: 10,
        address: "18 Henry st",
        city: "Cambridge",
        state: "MA",
        zip: "01742",
        age: "12",
        title: "Player10",        
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet"        
    },
    {
        id: 11,
        address: "18 Henry st",
        city: "Cambridge",
        state: "MA",
        zip: "01742",
        age: "12",
        title: "Player11",        
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet"        
    },
    {
        id: 12,
        address: "18 Henry st",
        city: "Cambridge",
        state: "MA",
        zip: "01742",
        age: "12",
        title: "Player12",        
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet"        
    }

];

export default properties;
